### ISSUE TITLE
Can't get example working

### ISSUE THREAD

**Issue by vincentwyshan** [schovi/react-iscroll#16]
ReferenceError: Unknown plugin "syntax-class-properties" specified in "/Users/cada/Downloads/react-iscroll-master/.babelrc" at 1, attempted to resolve relative to "/Users/cada/Downloads/react-iscroll-master"

**Comment by schovi** [comment]
That is odd.
Try to remove node_modules, pull newest version and install packages from scratch.

**Comment by timdoes** [comment]
I am getting the same error on v.0.1.7

**Comment by schovi** [comment]
Hello after long time.

I did huge update to version 1, can you try it https://github.com/schovi/react-iscroll/pull/17

**Comment by dhammikas** [comment]
Guys, Is this issue fixed now? I'm kinda still getting it, it seems

**Comment by schovi** [comment]
@dhammikas hey. Are you trying latest 1.0.0 version? If you updated from older version maybe you need to remove node_modules and install them again. I had problem there too.

**Comment by Cloud33** [comment]
@schovi  I used 1.0.0 version, but there is a @vincentwyshan problem, error:
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! react-iscroll@1.0.0 compile: `babel -d dist/ src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-iscroll@1.0.0 compile script 'babel -d dist/ src/'.
npm ERR! This is most likely a problem with the react-iscroll package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel -d dist/ src/
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-iscroll
npm ERR! There is likely additional logging output above.

Because the package.JSON configuration causes?

**Comment by schovi** [comment]
Back after some time.
Try it again with this branch https://github.com/schovi/react-iscroll/tree/feature/update-dev-dependencies where I updated all dev dependencies to latest version. If problem persists, give me your node version, npm version and try to run `babel --version` (it will work only if you have babel installed globally and maybe that can cause problem).

**Comment by adityasaxena** [comment]
@schovi the branch does work with the additional babel plugin. thanks!

**Comment by schovi** [comment]
@adityasaxena Merged and published https://github.com/schovi/react-iscroll/tree/1.0.2
